### ISSUE TITLE
Feature Request: Support installing additional plugins

### ISSUE THREAD

**Issue by justyns** [VirtusLab/jenkins-operator#5]
I see that you can override `basePlugins` in the CR yaml by specifying `spec.master.plugins` with something like this:

```
apiVersion: virtuslab.com/v1alpha1
kind: Jenkins
metadata:
  name: example
spec:
  master:
   image: jenkins/jenkins:lts
   plugins:
     configuration-as-code:1.4:
     - configuration-as-code-support:1.4
...
```

However, this either uses the default plugins OR the ones specified:
https://github.com/VirtusLab/jenkins-operator/blob/a275ed62d5a3e01ef5ed5e333ce6860b84a8f05f/pkg/controller/jenkins/jenkins_controller.go#L221-L224

As far as I understand, we have two options if we want to install additional plugins or update plugins:

1. Override `spec.master.plugins` with a complete list of plugins and dependencies.  This makes it difficult to maintain if `jenkins-operator` has a new release that uses a new set of base plugins.
2. Write custom .groovy scripts that install the needed plugins.  I believe this is the current recommendation in the README.

Let me know if there is another option I'm missing.

My feature request is to add a new option `spec.master.additionalPlugins` that would just be merged into the default set of plugins.  This would make managing plugins a little bit simpler compared to either option I listed, since only the updated or new plugins would need to be specified.
